# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 838)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 921, 791))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 160, 431, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.comp2_input = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.comp2_input.setGeometry(QtCore.QRect(0, 30, 421, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comp2_input.setFont(font)
        self.comp2_input.setObjectName("comp2_input")
        self.status = QtWidgets.QLabel(self.tab)
        self.status.setGeometry(QtCore.QRect(170, 650, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status.setFont(font)
        self.status.setFrameShape(QtWidgets.QFrame.Box)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 420, 431, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.comp4_input = QtWidgets.QPlainTextEdit(self.groupBox_7)
        self.comp4_input.setGeometry(QtCore.QRect(0, 30, 421, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comp4_input.setFont(font)
        self.comp4_input.setPlainText("")
        self.comp4_input.setObjectName("comp4_input")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 431, 241))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setGeometry(QtCore.QRect(350, 40, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(350, 200, 91, 16))
        self.label_13.setObjectName("label_13")
        self.email_input = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.email_input.setGeometry(QtCore.QRect(0, 30, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.email_input.setFont(font)
        self.email_input.setObjectName("email_input")
        self.address_input = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.address_input.setGeometry(QtCore.QRect(0, 110, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.address_input.setFont(font)
        self.address_input.setObjectName("address_input")
        self.mnemonic_input = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.mnemonic_input.setGeometry(QtCore.QRect(0, 180, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mnemonic_input.setFont(font)
        self.mnemonic_input.setObjectName("mnemonic_input")
        self.label_10 = QtWidgets.QLabel(self.groupBox_8)
        self.label_10.setGeometry(QtCore.QRect(350, 120, 71, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(480, 300, 431, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 421, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min_char_number = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.min_char_number.setMinimum(6)
        self.min_char_number.setMaximum(20)
        self.min_char_number.setProperty("value", 6)
        self.min_char_number.setObjectName("min_char_number")
        self.horizontalLayout.addWidget(self.min_char_number)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 60, 421, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.max_char_number = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.max_char_number.setMinimum(12)
        self.max_char_number.setMaximum(40)
        self.max_char_number.setProperty("value", 20)
        self.max_char_number.setObjectName("max_char_number")
        self.horizontalLayout_2.addWidget(self.max_char_number)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 560, 891, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.StartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.horizontalLayout_3.addWidget(self.StartButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(100, 660, 61, 16))
        self.label.setObjectName("label")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_14.setGeometry(QtCore.QRect(470, 420, 441, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_14)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 421, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lcdNumber.setPalette(palette)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(15)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_14)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 421, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lcdNumber_used = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_4)
        self.lcdNumber_used.setDigitCount(15)
        self.lcdNumber_used.setObjectName("lcdNumber_used")
        self.horizontalLayout_7.addWidget(self.lcdNumber_used)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 280, 431, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.comp3_input = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.comp3_input.setGeometry(QtCore.QRect(0, 30, 421, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comp3_input.setFont(font)
        self.comp3_input.setObjectName("comp3_input")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 10, 431, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.comp1_input = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.comp1_input.setGeometry(QtCore.QRect(0, 30, 421, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comp1_input.setFont(font)
        self.comp1_input.setObjectName("comp1_input")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 10, 291, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 120, 281, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.esalt_char_multible = QtWidgets.QCheckBox(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.esalt_char_multible.setFont(font)
        self.esalt_char_multible.setChecked(False)
        self.esalt_char_multible.setObjectName("esalt_char_multible")
        self.horizontalLayout_11.addWidget(self.esalt_char_multible)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.esalt_null = QtWidgets.QCheckBox(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.esalt_null.setFont(font)
        self.esalt_null.setChecked(False)
        self.esalt_null.setObjectName("esalt_null")
        self.horizontalLayout_11.addWidget(self.esalt_null)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 80, 281, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.esalt_char = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.esalt_char.setFont(font)
        self.esalt_char.setObjectName("esalt_char")
        self.horizontalLayout_10.addWidget(self.esalt_char)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 20, 281, 61))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.esalt_number = QtWidgets.QSpinBox(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.esalt_number.setFont(font)
        self.esalt_number.setMaximum(4)
        self.esalt_number.setProperty("value", 1)
        self.esalt_number.setObjectName("esalt_number")
        self.horizontalLayout_16.addWidget(self.esalt_number)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 80, 281, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lsalt_char = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lsalt_char.setFont(font)
        self.lsalt_char.setObjectName("lsalt_char")
        self.horizontalLayout_6.addWidget(self.lsalt_char)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 120, 281, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lsalt_char_multible = QtWidgets.QCheckBox(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lsalt_char_multible.setFont(font)
        self.lsalt_char_multible.setChecked(True)
        self.lsalt_char_multible.setObjectName("lsalt_char_multible")
        self.horizontalLayout_9.addWidget(self.lsalt_char_multible)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.lsalt_null = QtWidgets.QCheckBox(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lsalt_null.setFont(font)
        self.lsalt_null.setChecked(True)
        self.lsalt_null.setObjectName("lsalt_null")
        self.horizontalLayout_9.addWidget(self.lsalt_null)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(10, 20, 281, 61))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lsalt_number = QtWidgets.QSpinBox(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lsalt_number.setFont(font)
        self.lsalt_number.setMinimum(0)
        self.lsalt_number.setMaximum(4)
        self.lsalt_number.setProperty("value", 2)
        self.lsalt_number.setObjectName("lsalt_number")
        self.horizontalLayout_17.addWidget(self.lsalt_number)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_17.addWidget(self.label_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 10, 301, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 120, 291, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.vsalt_char_multible = QtWidgets.QCheckBox(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vsalt_char_multible.setFont(font)
        self.vsalt_char_multible.setChecked(True)
        self.vsalt_char_multible.setObjectName("vsalt_char_multible")
        self.horizontalLayout_14.addWidget(self.vsalt_char_multible)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.vsalt_null = QtWidgets.QCheckBox(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vsalt_null.setFont(font)
        self.vsalt_null.setChecked(False)
        self.vsalt_null.setObjectName("vsalt_null")
        self.horizontalLayout_14.addWidget(self.vsalt_null)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(10, 80, 291, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.vsalt_char = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vsalt_char.setFont(font)
        self.vsalt_char.setObjectName("vsalt_char")
        self.horizontalLayout_15.addWidget(self.vsalt_char)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(10, 19, 291, 61))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.vsalt_number = QtWidgets.QSpinBox(self.horizontalLayoutWidget_14)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vsalt_number.setFont(font)
        self.vsalt_number.setMinimum(0)
        self.vsalt_number.setMaximum(4)
        self.vsalt_number.setProperty("value", 2)
        self.vsalt_number.setObjectName("vsalt_number")
        self.horizontalLayout_18.addWidget(self.vsalt_number)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 270, 911, 451))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.groupBox_15.setPalette(palette)
        self.groupBox_15.setObjectName("groupBox_15")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_12.setGeometry(QtCore.QRect(530, 120, 371, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_12.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setFlat(False)
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_17 = QtWidgets.QLabel(self.groupBox_12)
        self.label_17.setGeometry(QtCore.QRect(10, 66, 281, 20))
        self.label_17.setObjectName("label_17")
        self.comp2_capitalize_all = QtWidgets.QCheckBox(self.groupBox_12)
        self.comp2_capitalize_all.setGeometry(QtCore.QRect(10, 190, 281, 17))
        self.comp2_capitalize_all.setObjectName("comp2_capitalize_all")
        self.comp2_char_set = QtWidgets.QPlainTextEdit(self.groupBox_12)
        self.comp2_char_set.setGeometry(QtCore.QRect(10, 90, 361, 31))
        self.comp2_char_set.setPlainText("")
        self.comp2_char_set.setObjectName("comp2_char_set")
        self.comp2_capitalize_first = QtWidgets.QCheckBox(self.groupBox_12)
        self.comp2_capitalize_first.setGeometry(QtCore.QRect(10, 130, 281, 17))
        self.comp2_capitalize_first.setObjectName("comp2_capitalize_first")
        self.comp2_noclue = QtWidgets.QCheckBox(self.groupBox_12)
        self.comp2_noclue.setGeometry(QtCore.QRect(10, 30, 231, 31))
        self.comp2_noclue.setObjectName("comp2_noclue")
        self.comp2_min_char = QtWidgets.QSpinBox(self.groupBox_12)
        self.comp2_min_char.setGeometry(QtCore.QRect(10, 230, 42, 22))
        self.comp2_min_char.setMinimum(1)
        self.comp2_min_char.setMaximum(8)
        self.comp2_min_char.setObjectName("comp2_min_char")
        self.label_18 = QtWidgets.QLabel(self.groupBox_12)
        self.label_18.setGeometry(QtCore.QRect(70, 230, 291, 21))
        self.label_18.setObjectName("label_18")
        self.comp2_max_char = QtWidgets.QSpinBox(self.groupBox_12)
        self.comp2_max_char.setGeometry(QtCore.QRect(10, 260, 42, 22))
        self.comp2_max_char.setMinimum(1)
        self.comp2_max_char.setMaximum(8)
        self.comp2_max_char.setObjectName("comp2_max_char")
        self.comp2_max_cha_lable = QtWidgets.QLabel(self.groupBox_12)
        self.comp2_max_cha_lable.setGeometry(QtCore.QRect(70, 260, 291, 21))
        self.comp2_max_cha_lable.setObjectName("comp2_max_cha_lable")
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setGeometry(QtCore.QRect(70, 290, 291, 21))
        self.label_22.setObjectName("label_22")
        self.comp2_repeat_char = QtWidgets.QSpinBox(self.groupBox_12)
        self.comp2_repeat_char.setGeometry(QtCore.QRect(10, 290, 42, 22))
        self.comp2_repeat_char.setMinimum(1)
        self.comp2_repeat_char.setMaximum(5)
        self.comp2_repeat_char.setObjectName("comp2_repeat_char")
        self.comp2_capitalize_each = QtWidgets.QCheckBox(self.groupBox_12)
        self.comp2_capitalize_each.setGeometry(QtCore.QRect(10, 160, 209, 22))
        self.comp2_capitalize_each.setObjectName("comp2_capitalize_each")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 120, 381, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_10.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(10, 66, 281, 20))
        self.label_15.setObjectName("label_15")
        self.comp1_char_set = QtWidgets.QPlainTextEdit(self.groupBox_10)
        self.comp1_char_set.setGeometry(QtCore.QRect(10, 90, 361, 31))
        self.comp1_char_set.setPlainText("")
        self.comp1_char_set.setObjectName("comp1_char_set")
        self.comp1_noclue = QtWidgets.QCheckBox(self.groupBox_10)
        self.comp1_noclue.setGeometry(QtCore.QRect(10, 30, 231, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comp1_noclue.setFont(font)
        self.comp1_noclue.setObjectName("comp1_noclue")
        self.comp1_capitalize_first = QtWidgets.QCheckBox(self.groupBox_10)
        self.comp1_capitalize_first.setGeometry(QtCore.QRect(10, 130, 209, 22))
        self.comp1_capitalize_first.setObjectName("comp1_capitalize_first")
        self.comp1_capitalize_each = QtWidgets.QCheckBox(self.groupBox_10)
        self.comp1_capitalize_each.setGeometry(QtCore.QRect(10, 160, 209, 22))
        self.comp1_capitalize_each.setObjectName("comp1_capitalize_each")
        self.comp1_min_char = QtWidgets.QSpinBox(self.groupBox_10)
        self.comp1_min_char.setGeometry(QtCore.QRect(10, 230, 42, 22))
        self.comp1_min_char.setMinimum(1)
        self.comp1_min_char.setMaximum(8)
        self.comp1_min_char.setObjectName("comp1_min_char")
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setGeometry(QtCore.QRect(70, 260, 291, 21))
        self.label_19.setObjectName("label_19")
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setGeometry(QtCore.QRect(70, 230, 291, 21))
        self.label_16.setObjectName("label_16")
        self.comp1_max_char = QtWidgets.QSpinBox(self.groupBox_10)
        self.comp1_max_char.setGeometry(QtCore.QRect(10, 260, 42, 22))
        self.comp1_max_char.setMinimum(1)
        self.comp1_max_char.setMaximum(8)
        self.comp1_max_char.setProperty("value", 3)
        self.comp1_max_char.setObjectName("comp1_max_char")
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setGeometry(QtCore.QRect(70, 290, 291, 21))
        self.label_21.setObjectName("label_21")
        self.comp1_repeat_char = QtWidgets.QSpinBox(self.groupBox_10)
        self.comp1_repeat_char.setGeometry(QtCore.QRect(10, 290, 42, 22))
        self.comp1_repeat_char.setMinimum(1)
        self.comp1_repeat_char.setMaximum(5)
        self.comp1_repeat_char.setObjectName("comp1_repeat_char")
        self.comp1_capitalize_all = QtWidgets.QCheckBox(self.groupBox_10)
        self.comp1_capitalize_all.setGeometry(QtCore.QRect(10, 190, 209, 22))
        self.comp1_capitalize_all.setObjectName("comp1_capitalize_all")
        self.label_26 = QtWidgets.QLabel(self.groupBox_15)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 901, 41))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_15)
        self.label_27.setGeometry(QtCore.QRect(6, 33, 900, 31))
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(self.groupBox_15)
        self.label_30.setGeometry(QtCore.QRect(10, 52, 671, 31))
        self.label_30.setObjectName("label_30")
        self.label_24 = QtWidgets.QLabel(self.groupBox_15)
        self.label_24.setGeometry(QtCore.QRect(10, 73, 191, 30))
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 942, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comp1_noclue.clicked['bool'].connect(self.comp1_input.setDisabled)
        self.comp2_noclue.clicked['bool'].connect(self.comp2_input.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Component 2"))
        self.comp2_input.setPlainText(_translate("MainWindow", "ETC BAT GO"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Component 4"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Tezos ICO credentials"))
        self.label_9.setText(_translate("MainWindow", "email"))
        self.label_13.setText(_translate("MainWindow", "mnemonic"))
        self.email_input.setPlainText(_translate("MainWindow", "cujo@outlook.com"))
        self.address_input.setPlainText(_translate("MainWindow", "tz1eyb15LvxJC23cBkYNNA84MYkwWmx2JmxJ"))
        self.mnemonic_input.setPlainText(_translate("MainWindow", "grace zebra yard dose flush myself brand apple night start tube flock embody payment marble"))
        self.label_10.setText(_translate("MainWindow", "address"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Password length limits"))
        self.label_2.setText(_translate("MainWindow", "min number of PWD characters"))
        self.label_5.setText(_translate("MainWindow", "max number of PWD characters"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Status"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Expected number of passwords"))
        self.label_6.setText(_translate("MainWindow", "total PWD candidates"))
        self.label_8.setText(_translate("MainWindow", "used PWD candidates"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Component 3"))
        self.comp3_input.setPlainText(_translate("MainWindow", "1990 2020"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Component 1"))
        self.comp1_input.setPlainText(_translate("MainWindow", "Charles CHARLES Ch@rles Jimmy Jonny Eli$abeth"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "BASIC"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Ending salt configuration"))
        self.esalt_char_multible.setText(_translate("MainWindow", "repeat char possible"))
        self.esalt_null.setText(_translate("MainWindow", "null possible"))
        self.esalt_char.setText(_translate("MainWindow", "!?"))
        self.label_7.setText(_translate("MainWindow", "characters"))
        self.label_11.setText(_translate("MainWindow", "maximum number of ending salt characters to be used in PWD "))
        self.groupBox.setTitle(_translate("MainWindow", "Leading salt configuration"))
        self.lsalt_char.setText(_translate("MainWindow", "$?!"))
        self.label_3.setText(_translate("MainWindow", "characters"))
        self.lsalt_char_multible.setText(_translate("MainWindow", "repeat char possible"))
        self.lsalt_null.setText(_translate("MainWindow", "null possible"))
        self.label_4.setText(_translate("MainWindow", "maximum number of leading salt characters to be used in PWD "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Variable salt configuration"))
        self.vsalt_char_multible.setText(_translate("MainWindow", "repeat char possible"))
        self.vsalt_null.setText(_translate("MainWindow", "null possible"))
        self.vsalt_char.setText(_translate("MainWindow", "!?%"))
        self.label_12.setText(_translate("MainWindow", "characters"))
        self.label_14.setText(_translate("MainWindow", "maximum number of variable salt characters to be used in PWD "))
        self.groupBox_15.setTitle(_translate("MainWindow", "!!! Attention !!!"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Component 2 advanced"))
        self.label_17.setText(_translate("MainWindow", "Characterset to build Component 1"))
        self.comp2_capitalize_all.setText(_translate("MainWindow", "try capitalize all letters"))
        self.comp2_capitalize_first.setText(_translate("MainWindow", "try capitalize first letter"))
        self.comp2_noclue.setText(_translate("MainWindow", "no guess for Component 2 at all"))
        self.label_18.setText(_translate("MainWindow", "min. number of char. for Component 2"))
        self.comp2_max_cha_lable.setText(_translate("MainWindow", "max. number of char. for Component 2"))
        self.label_22.setText(_translate("MainWindow", "max. number of repeating characters"))
        self.comp2_capitalize_each.setText(_translate("MainWindow", "try capitalize each letters"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Component 1 advanced"))
        self.label_15.setText(_translate("MainWindow", "Characterset to build Component 1"))
        self.comp1_noclue.setText(_translate("MainWindow", "no guess for Component 1 at all"))
        self.comp1_capitalize_first.setText(_translate("MainWindow", "try capitalize first letter"))
        self.comp1_capitalize_each.setText(_translate("MainWindow", "try capitalize each letters"))
        self.label_19.setText(_translate("MainWindow", "max. number of char. for Component 1"))
        self.label_16.setText(_translate("MainWindow", "min. number of char. for Component 1"))
        self.label_21.setText(_translate("MainWindow", "max. number of repeating characters"))
        self.comp1_capitalize_all.setText(_translate("MainWindow", "try capitalize all letters"))
        self.label_26.setText(_translate("MainWindow", "Use this Part only in case you are absolutly desperate. Using these options will increase number of potential passwords"))
        self.label_27.setText(_translate("MainWindow", " and respective time to analyse dramatically! There is absolutly no backup implemented."))
        self.label_30.setText(_translate("MainWindow", "In case system crashes you have to re-start from scratch!!"))
        self.label_24.setText(_translate("MainWindow", "Check README for hints!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "ADVANCED"))


